sudo: false

language:
    - php
    - node_js

php:
    - 5.2
    - 5.4

node_js:
    - 0.10

env:
    - WP_MULTISITE=0
    - WP_MULTISITE=1

branches:
    only:
        - master

before_script:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - mkdir /tmp/wordpress && curl -L https://github.com/xwp/wordpress-develop/archive/feature/menu-customizer.tar.gz | tar --strip-components=1 -zx -C /tmp/wordpress
    - source $DEV_LIB_PATH/travis.before_script.sh

script:
    - $DEV_LIB_PATH/travis.script.sh

after_script:
    - $DEV_LIB_PATH/travis.after_script.sh
